# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0022_auto_20160820_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='magic_token_ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 12, 5, 46, 532355, tzinfo=utc)),
        ),
    ]
