# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 16:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import magicauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_token', models.CharField(default=magicauth.models.generate_magic_token, max_length=44, unique=True)),
                ('magic_token_ttl', models.DateTimeField(default=datetime.datetime(2016, 12, 3, 17, 3, 54, 577291, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
