# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magicauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magictoken',
            name='magic_token_ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 17, 20, 7, 27288, tzinfo=utc)),
        ),
    ]
